### ISSUE TITLE
8月23號我拷貝你的源碼 能正常編譯出ssr-p 9月3號我拷貝了一下，發現不行編譯

### ISSUE THREAD

**Issue by falmovet** [Tonkercke/openwrt#1]
Configuring kmod-e1000.
Configuring rtl8821ae-firmware.
Configuring kmod-rtl8821ae.
Collected errors:
Configuring ca-certificates.
 * check_data_file_clashes: Package libustream-openssl20201210 wants to install file /workdir/openwrt/build_dir/target-x86_64_musl/root-x86/lib/libustream-ssl.so
Configuring vim.
	But that file is already provided by package  * libustream-wolfssl20201210
Configuring rt73-usb-firmware.
 * opkg_install_cmd: Cannot install package libustream-openssl20201210.
Configuring uhttpd.
 * check_data_file_clashes: Package libustream-openssl20201210 wants to install file /workdir/openwrt/build_dir/target-x86_64_musl/root-x86/lib/libustream-ssl.so
Configuring ip6tables.
	But that file is already provided by package  * libustream-wolfssl20201210
Configuring kmod-arptables.
 * opkg_install_cmd: Cannot install package luci-app-ssr-plus.
Configuring kmod-forcedeth.
make[2]: *** [package/Makefile:69: package/install] Error 255
Configuring luci-i18n-base-zh-cn.
Configuring tor-geoip.
Configuring kmod-usb-ohci-pci.

這是報錯的地方。

**Comment by falmovet** [comment]
看你今天更新了源碼  我再拷貝一份試試。

**Comment by falmovet** [comment]
還是編譯失敗了。

**Comment by Tonkercke** [comment]
這是因爲你在選擇一些插件的時候有些項目發生衝突了，比如下面這幾行：
check_data_file_clashes: Package libustream-openssl20201210 wants to install file /workdir/openwrt/build_dir/target-x86_64_musl/root-x86/lib/libustream-ssl.so
Configuring vim.
But that file is already provided by package * libustream-wolfssl20201210
Configuring rt73-usb-firmware.
libustream-ssl.so這項被重複選擇了，所以才會出現衝突導致編譯失敗。

編譯的時候一定要選擇自己用的到的插件，用不到的或者不清楚作用的最好不要選擇，不然會出現相互衝突導致編譯失敗。
